language: python

# We don't need sudo, and setting this to false means faster VM bootup.
sudo: false


branches:
  only:
    - master


install:
  - pip install tox


matrix:
  include:
    - python: 3.5
      env: TOXENV=pyflakes

    - python: 3.5
      env: TOXENV=py35-trial-coverage,coverage_combined

    - python: 3.6
      env: TOXENV=py36-trial-coverage,coverage_combined


script:
  - tox
