language: python


branches:
  only:
    - master


install:
  - pip install tox


matrix:
  include:
    - python: 3.5
      env: TOXENV=pyflakes

    - python: 3.5
      env: TOXENV=py35-trial-coverage

    - python: 3.5
      env: TOXENV=coverage_combined


script:
  - tox
