language: python

# We don't need sudo, and setting this to false means faster VM bootup.
sudo: false


branches:
  only:
    - master


install:
  - pip install tox


matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8

    - python: 3.6
      env: TOXENV=mypy

    - python: 3.6
      env: TOXENV=docs

    - python: 3.5
      env: TOXENV=py35-coverage,codecov

    - python: 3.6
      env: TOXENV=py36-coverage,codecov

    - python: 3.7-dev
      env: TOXENV=py37-coverage,codecov

  allow_failures:
    - env: TOX_ENV=py37-coverage,codecov

script:
  - tox
